<?php
declare(strict_types=1);require __DIR__.'/bootstrap.php';require_permission('media.manage');$pdo=db();
if($_SERVER['REQUEST_METHOD']==='POST'){try{verify_csrf();if(($_POST['action']??'')==='delete'){$st=$pdo->prepare('SELECT file_path FROM media_library WHERE id=?');$st->execute([(int)$_POST['id']]);$p=$st->fetchColumn();if($p&&str_starts_with((string)$p,'uploads/media/'))@unlink(ROOT_DIR.'/'.$p);$pdo->prepare('DELETE FROM media_library WHERE id=?')->execute([(int)$_POST['id']]);flash('success','Archivo eliminado.');}else{$f=$_FILES['file']??null;if(!$f||$f['error']!==UPLOAD_ERR_OK)throw new RuntimeException('Selecciona un archivo válido.');if((int)$f['size']>8*1024*1024)throw new RuntimeException('El archivo no puede superar 8 MB.');$mime=secure_file_mime_type($f['tmp_name']);$allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp','application/pdf'=>'pdf'];if(!isset($allowed[$mime]))throw new RuntimeException('Formato permitido: JPG, PNG, WEBP o PDF.');$dir=UPLOAD_DIR.'/media';if(!is_dir($dir))mkdir($dir,0755,true);$name=bin2hex(random_bytes(12)).'.'.$allowed[$mime];if(!move_uploaded_file($f['tmp_name'],$dir.'/'.$name))throw new RuntimeException('No se pudo guardar el archivo.');$pdo->prepare('INSERT INTO media_library(file_path,original_name,mime_type,file_size,alt_text) VALUES(?,?,?,?,?)')->execute(['uploads/media/'.$name,basename((string)$f['name']),$mime,(int)$f['size'],trim((string)($_POST['alt_text']??''))]);flash('success','Archivo agregado a la biblioteca.');}header('Location: media.php');exit;}catch(Throwable $e){flash('error',$e->getMessage());header('Location: media.php');exit;}}
$rows=$pdo->query('SELECT * FROM media_library ORDER BY id DESC')->fetchAll();$pageTitle='Media Library';$active='media';require __DIR__.'/_header.php';?>
<div class="page-heading"><div><p class="eyebrow">ARCHIVOS</p><h1>Media Library</h1><p class="muted">Imágenes y documentos reutilizables.</p></div></div>
<section class="panel"><form class="crud-form" method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>">
<div class="full admin-upload-field"><div class="field-heading"><div><strong>Archivo</strong><small>Arrastra y suelta, pega desde el portapapeles o selecciona un archivo. JPG, PNG, WEBP o PDF · máximo 8 MB.</small></div></div>
<div class="premium-media-zone" data-upload-zone tabindex="0" aria-label="Subir archivo a Media Library"><input class="visually-hidden-file" type="file" name="file" accept="image/jpeg,image/png,image/webp,application/pdf" data-max-files="1" data-max-total-bytes="8388608" data-empty-label="No hay archivo seleccionado."><div class="upload-icon" aria-hidden="true">⇧</div><strong>Arrastra y suelta el archivo aquí</strong><small>También puedes pegar con Ctrl + V o usar el selector.</small><button type="button" class="upload-zone-action" data-upload-choose>Seleccionar archivo</button><div class="upload-selection-name" data-upload-name>No hay archivo seleccionado.</div><div class="premium-upload-preview" data-upload-preview aria-live="polite"></div></div></div>
<label class="full">Texto alternativo<input name="alt_text"></label><div class="full form-actions"><button>Subir archivo</button></div></form></section>
<section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Vista</th><th>Archivo</th><th>Tamaño</th><th>Acciones</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?php if(str_starts_with($r['mime_type'],'image/')):?><img class="preview-thumb" src="../<?=h($r['file_path'])?>" alt=""><?php else:?>PDF<?php endif;?></td><td><a href="../<?=h($r['file_path'])?>" target="_blank"><?=h($r['original_name'])?></a><br><small><?=h($r['alt_text'])?></small></td><td><?=number_format($r['file_size']/1024,1)?> KB</td><td><div class="actions"><a class="button secondary small" href="../<?=h($r['file_path'])?>" target="_blank" rel="noopener">Ver</a><form method="post" data-premium-confirm data-confirm-title="Eliminar archivo" data-confirm-message="¿Eliminar este archivo? Esta acción no se puede deshacer." data-confirm-ok="Sí, eliminar" data-confirm-cancel="Cancelar"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="danger small">Eliminar</button></form></div></td></tr><?php endforeach;?></tbody></table></div></section><?php require __DIR__.'/_footer.php';?>
